spring:
  application:
    name: apollo-configservice
  datasource:
    url: jdbc:postgresql://localhost:5532/apollo-config
    username: growingio
    password: postgres
  profiles:
    active: dev
  cloud:
    consul:
      enabled: false
ctrip:
  appid: 100003171
server:
  port: 8080
logging:
  file:
    name: /Users/growingio/Documents/logs/apollo-configservice.log
eureka:
  instance:
    hostname: ${hostname:localhost}
    preferIpAddress: true
    status-page-url-path: /info
    health-check-url-path: /health
  server:
    peerEurekaNodesUpdateIntervalMs: 60000
    enableSelfPreservation: false
  client:
    serviceUrl:
      # This setting will be overridden by eureka.service.url setting from ApolloConfigDB.ServerConfig or System Property
      # see com.ctrip.framework.apollo.biz.eureka.ApolloEurekaClientConfig
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/
    healthcheck:
      enabled: true
    eurekaServiceUrlPollIntervalSeconds: 60
    fetch-registry: false
    registerWithEureka: false

management:
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP
